# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e456846b4bcb9772e51381b3b725b3463946ce6fa20c461e479ae017717d060faccdb0fa28cbb0de2f371e7ab8a379d559e707036e9b65daa65a3648d7dc2b8

test:
  secret_key_base: c6e50bab2e9d22ed209ce22b767ea9beb186966c23e297392a5272e94aebdbbc5412c119584ac2b4c4dc170d216b53cce1eb0c93edaa2b61b279d6be61053b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
